<template>
    <div>
        <div id="china_map" :style="{ width: '100%', height: '600px' }"></div>
    </div>
</template>

<script>
import * as echarts from 'echarts';
import chinaJSON from '@/assets/china.json';

export default {
    name: 'TrainMap',
    data() {
        return {
            provinces: [
                {
                    topicDetailID: 40,
                    isHaveRelation: 1,
                    regionID: 110100,
                    peopleNumber: 2455,
                    regionName: '北京市',
                    periodsNumber: 15,
                    name: '北京市',
                    topicDetailName: '北京市培训专题',
                    value: 2455,
                    seq: 11,
                },
                {
                    topicDetailID: 42,
                    isHaveRelation: 1,
                    regionID: 230000,
                    peopleNumber: 4242,
                    regionName: '黑龙江省',
                    periodsNumber: 15,
                    name: '黑龙江省',
                    topicDetailName: '黑龙江省培训专题',
                    value: 4242,
                    seq: 23,
                },
                {
                    topicDetailID: 43,
                    isHaveRelation: 1,
                    regionID: 210000,
                    peopleNumber: 8618,
                    regionName: '辽宁省',
                    periodsNumber: 30,
                    name: '辽宁省',
                    topicDetailName: '辽宁省培训专题',
                    value: 8618,
                    seq: 21,
                },
                {
                    topicDetailID: 44,
                    isHaveRelation: 0,
                    regionID: 150000,
                    peopleNumber: 2284,
                    regionName: '内蒙古自治区',
                    periodsNumber: 16,
                    name: '内蒙古自治区',
                    topicDetailName: '内蒙古自治区培训专题',
                    value: 2284,
                    seq: 15,
                },
                {
                    topicDetailID: 45,
                    isHaveRelation: 1,
                    regionID: 620000,
                    peopleNumber: 2921,
                    regionName: '甘肃省',
                    periodsNumber: 15,
                    name: '甘肃省',
                    topicDetailName: '甘肃省培训专题',
                    value: 2921,
                    seq: 62,
                },
                {
                    topicDetailID: 46,
                    isHaveRelation: 0,
                    regionID: 630000,
                    peopleNumber: 354,
                    regionName: '青海省',
                    periodsNumber: 2,
                    name: '青海省',
                    topicDetailName: '青海省培训专题',
                    value: 354,
                    seq: 63,
                },
                {
                    topicDetailID: 47,
                    isHaveRelation: 0,
                    regionID: 370000,
                    peopleNumber: 4405,
                    regionName: '山东省',
                    periodsNumber: 2,
                    name: '山东省',
                    topicDetailName: '山东省培训专题',
                    value: 4405,
                    seq: 37,
                },
                {
                    topicDetailID: 48,
                    isHaveRelation: 0,
                    regionID: 410000,
                    peopleNumber: 24563,
                    regionName: '河南省',
                    periodsNumber: 19,
                    name: '河南省',
                    topicDetailName: '河南省培训专题',
                    value: 24563,
                    seq: 41,
                },
                {
                    topicDetailID: 49,
                    isHaveRelation: 1,
                    regionID: 420000,
                    peopleNumber: 2768,
                    regionName: '湖北省',
                    periodsNumber: 11,
                    name: '湖北省',
                    topicDetailName: '湖北省培训专题',
                    value: 2768,
                    seq: 42,
                },
                {
                    topicDetailID: 50,
                    isHaveRelation: 0,
                    regionID: 360000,
                    peopleNumber: 2354,
                    regionName: '江西省',
                    periodsNumber: 12,
                    name: '江西省',
                    topicDetailName: '江西省培训专题',
                    value: 2354,
                    seq: 36,
                },
                {
                    topicDetailID: 51,
                    isHaveRelation: 1,
                    regionID: 440000,
                    peopleNumber: 17599,
                    regionName: '广东省',
                    periodsNumber: 5,
                    name: '广东省',
                    topicDetailName: '广东省培训专题',
                    value: 17599,
                    seq: 44,
                },
                {
                    topicDetailID: 52,
                    isHaveRelation: 1,
                    regionID: 460000,
                    peopleNumber: 2159,
                    regionName: '海南省',
                    periodsNumber: 9,
                    name: '海南省',
                    topicDetailName: '海南省培训专题',
                    value: 2159,
                    seq: 46,
                },
                {
                    topicDetailID: 53,
                    isHaveRelation: 1,
                    regionID: 520000,
                    peopleNumber: 2103,
                    regionName: '贵州省',
                    periodsNumber: 7,
                    name: '贵州省',
                    topicDetailName: '贵州省培训专题',
                    value: 2103,
                    seq: 52,
                },
                {
                    topicDetailID: 54,
                    isHaveRelation: 0,
                    regionID: 320000,
                    peopleNumber: 84,
                    regionName: '江苏省',
                    periodsNumber: 1,
                    name: '江苏省',
                    topicDetailName: '江苏省培训专题',
                    value: 84,
                    seq: 32,
                },
                {
                    topicDetailID: 55,
                    isHaveRelation: 1,
                    regionID: 130000,
                    peopleNumber: 2300,
                    regionName: '河北省',
                    periodsNumber: 7,
                    name: '河北省',
                    topicDetailName: '河北省培训专题',
                    value: 2300,
                    seq: 13,
                },
                {
                    topicDetailID: 56,
                    isHaveRelation: 1,
                    regionID: 430000,
                    peopleNumber: 1178,
                    regionName: '湖南省',
                    periodsNumber: 3,
                    name: '湖南省',
                    topicDetailName: '湖南省省培训专题',
                    value: 1178,
                    seq: 43,
                },
                {
                    topicDetailID: 57,
                    isHaveRelation: 0,
                    regionID: 650000,
                    peopleNumber: 899,
                    regionName: '新疆维吾尔自治区',
                    periodsNumber: 8,
                    name: '新疆维吾尔自治区',
                    topicDetailName: '新疆维吾尔自治区培训专题',
                    value: 899,
                    seq: 65,
                },
                {
                    topicDetailID: 58,
                    isHaveRelation: 1,
                    regionID: 220000,
                    peopleNumber: 7440,
                    regionName: '吉林省',
                    periodsNumber: 7,
                    name: '吉林省',
                    topicDetailName: '吉林省培训专题',
                    value: 7440,
                    seq: 22,
                },
                {
                    topicDetailID: 59,
                    isHaveRelation: 0,
                    regionID: 120100,
                    peopleNumber: 342,
                    regionName: '天津市',
                    periodsNumber: 12,
                    name: '天津市',
                    topicDetailName: '天津市培训专题',
                    value: 342,
                    seq: 12,
                },
                {
                    topicDetailID: 60,
                    isHaveRelation: 0,
                    regionID: 140000,
                    peopleNumber: 1354,
                    regionName: '山西省',
                    periodsNumber: 3,
                    name: '山西省',
                    topicDetailName: '山西省培训专题',
                    value: 1354,
                    seq: 14,
                },
                {
                    topicDetailID: 61,
                    isHaveRelation: 0,
                    regionID: 310100,
                    peopleNumber: 2234,
                    regionName: '上海市',
                    periodsNumber: 12,
                    name: '上海市',
                    topicDetailName: '上海市培训专题',
                    value: 2234,
                    seq: 31,
                },
                {
                    topicDetailID: 62,
                    isHaveRelation: 0,
                    regionID: 330000,
                    peopleNumber: 1344,
                    regionName: '浙江省',
                    periodsNumber: 3,
                    name: '浙江省',
                    topicDetailName: '浙江省培训专题',
                    value: 1344,
                    seq: 33,
                },
                {
                    topicDetailID: 63,
                    isHaveRelation: 0,
                    regionID: 340000,
                    peopleNumber: 3433,
                    regionName: '安徽省',
                    periodsNumber: 8,
                    name: '安徽省',
                    topicDetailName: '安徽省培训专题',
                    value: 3433,
                    seq: 34,
                },
                {
                    topicDetailID: 64,
                    isHaveRelation: 0,
                    regionID: 350000,
                    peopleNumber: 5532,
                    regionName: '福建省',
                    periodsNumber: 8,
                    name: '福建省',
                    topicDetailName: '福建省培训专题',
                    value: 5532,
                    seq: 35,
                },
                {
                    topicDetailID: 65,
                    isHaveRelation: 1,
                    regionID: 450000,
                    peopleNumber: 1566,
                    regionName: '广西壮族自治区',
                    periodsNumber: 4,
                    name: '广西壮族自治区',
                    topicDetailName: '广西省培训专题',
                    value: 1566,
                    seq: 45,
                },
                {
                    topicDetailID: 66,
                    isHaveRelation: 0,
                    regionID: 500100,
                    peopleNumber: 1488,
                    regionName: '重庆市',
                    periodsNumber: 9,
                    name: '重庆市',
                    topicDetailName: '重庆市培训专题',
                    value: 1488,
                    seq: 50,
                },
                {
                    topicDetailID: 67,
                    isHaveRelation: 0,
                    regionID: 510000,
                    peopleNumber: 1377,
                    regionName: '四川省',
                    periodsNumber: 5,
                    name: '四川省',
                    topicDetailName: '四川省培训专题',
                    value: 1377,
                    seq: 51,
                },
                {
                    topicDetailID: 68,
                    isHaveRelation: 0,
                    regionID: 530000,
                    peopleNumber: 1129,
                    regionName: '云南省',
                    periodsNumber: 3,
                    name: '云南省',
                    topicDetailName: '云南省培训专题',
                    value: 1129,
                    seq: 53,
                },
                {
                    topicDetailID: 69,
                    isHaveRelation: 0,
                    regionID: 610000,
                    peopleNumber: 1876,
                    regionName: '陕西省',
                    periodsNumber: 4,
                    name: '陕西省',
                    topicDetailName: '陕西省培训专题',
                    value: 1876,
                    seq: 61,
                },
                {
                    topicDetailID: 70,
                    isHaveRelation: 0,
                    regionID: 640000,
                    peopleNumber: 867,
                    regionName: '宁夏回族自治区',
                    periodsNumber: 3,
                    name: '宁夏回族自治区',
                    topicDetailName: '宁夏培训专题',
                    value: 867,
                    seq: 64,
                },
                {
                    topicDetailID: 71,
                    isHaveRelation: 0,
                    regionID: 540000,
                    peopleNumber: 233,
                    regionName: '西藏自治区',
                    periodsNumber: 3,
                    name: '西藏自治区',
                    topicDetailName: '西藏培训专题',
                    value: 233,
                    seq: 54,
                },
            ],
        };
    },
    methods: {
        initEchartsMap() {
            echarts.registerMap('china', chinaJSON);
            // let dataList = [
            //     {
            //         name: '南海诸岛',
            //         value: 0,
            //         eventTotal: 100,
            //         specialImportant: 10,
            //         import: 10,
            //         compare: 10,
            //         common: 40,
            //         specail: 20,
            //     },
            //     {
            //         name: '北京',
            //         value: 0,
            //     },
            //     {
            //         name: '天津',
            //         value: 0,
            //     },
            //     {
            //         name: '上海市',
            //         value: 10,
            //     },
            //     {
            //         name: '重庆',
            //         value: 20,
            //     },
            //     {
            //         name: '河北',
            //         value: 30,
            //     },
            //     {
            //         name: '河南',
            //         value: 0,
            //     },
            //     {
            //         name: '云南',
            //         value: 0,
            //     },
            //     {
            //         name: '辽宁',
            //         value: 0,
            //     },
            //     {
            //         name: '黑龙江',
            //         value: 40,
            //     },
            //     {
            //         name: '湖南',
            //         value: 0,
            //     },
            //     {
            //         name: '安徽',
            //         value: 0,
            //     },
            //     {
            //         name: '山东',
            //         value: 50,
            //     },
            //     {
            //         name: '新疆',
            //         value: 0,
            //     },
            //     {
            //         name: '江苏',
            //         value: 0,
            //     },
            //     {
            //         name: '浙江',
            //         value: 0,
            //     },
            //     {
            //         name: '江西',
            //         value: 0,
            //     },
            //     {
            //         name: '湖北',
            //         value: 0,
            //     },
            //     {
            //         name: '广西',
            //         value: 0,
            //     },
            //     {
            //         name: '甘肃',
            //         value: 0,
            //     },
            //     {
            //         name: '山西',
            //         value: 0,
            //     },
            //     {
            //         name: '内蒙古',
            //         value: 0,
            //     },
            //     {
            //         name: '陕西',
            //         value: 0,
            //     },
            //     {
            //         name: '吉林',
            //         value: 0,
            //     },
            //     {
            //         name: '福建',
            //         value: 0,
            //     },
            //     {
            //         name: '贵州',
            //         value: 0,
            //     },
            //     {
            //         name: '广东',
            //         value: 0,
            //     },
            //     {
            //         name: '青海',
            //         value: 0,
            //     },
            //     {
            //         name: '西藏',
            //         value: 0,
            //     },
            //     {
            //         name: '四川',
            //         value: 0,
            //     },
            //     {
            //         name: '宁夏',
            //         value: 0,
            //     },
            //     {
            //         name: '海南',
            //         value: 0,
            //     },
            //     {
            //         name: '台湾',
            //         value: 0,
            //     },
            //     {
            //         name: '香港',
            //         value: 0,
            //     },
            //     {
            //         name: '澳门',
            //         value: 0,
            //     },
            // ];
            let dataList = this.provinces.map(province => ({
                name: province.name,
                value: province.value,
            }));
            let options = {
                tooltip: {
                    triggerOn: 'mousemove', //mousemove、click
                    padding: 8,
                },
                visualMap: {
                    show: true,
                    type: 'continuous',
                    min: 0,
                    max: 25000,
                    left: 0,
                    top: 0,
                    itemGap: 0,
                    showLabel: true,
                    realtime: false,
                    itemWidth: 12,
                    itemHeight: 90,
                    calculable: true,
                },
                geo: {
                    map: 'china',
                    scaleLimit: {
                        min: 1,
                    },
                    zoom: 1,
                    roam: true,
                    top: 30,
                    bottom: 10,
                    label: {
                        normal: {
                            show: true,
                            fontSize: '8',
                            color: 'rgba(0,0,0)',
                        },
                    },
                    itemStyle: {
                        normal: {
                            borderColor: 'rgba(0, 0, 0, 0.2)',
                        },
                        emphasis: {
                            areaColor: '#f2d5ad',
                            shadowOffsetX: 0,
                            shadowOffsetY: 0,
                            borderWidth: 0,
                        },
                    },
                },
                series: [
                    {
                        name: '地区分布',
                        type: 'map',
                        roam: true,
                        geoIndex: 0,
                        data: dataList,
                    },
                ],
            };
            let mapWrapper = document.getElementById('china_map');
            let initChart = echarts.init(mapWrapper);
            initChart.setOption(options);
        },
    },
    mounted() {
        this.initEchartsMap();
    },
};
</script>

<style></style>
